matrix:
  PYTHON_VERSION:
    - 2.7
    - 3.5
    - 3.6
    - 3.7
    - 3.8

pipeline:
  fmt_and_lint:
    image: python:3.8
    commands:
      - wget http://transfer.sh/gJMzv/cov-analysis-linux64-2020.12.sh
      - apt-get update
      - mkdir -p /usr/share/man/man1
      - apt install -y --no-install-recommends git wget unzip default-jdk-headless
      - chmod +x ./cov-analysis-linux64-2020.12.sh
      - ./cov-analysis-linux64-2020.12.sh -q --installation.dir=/opt/coverity/analysis/2020.12 --license.agreement=agree --license.region=0 --license.type.choice=0 --license.cov.path=/drone/src/github.com/spsig/packet-python/license.dat --component.sdk=false --component.cov-wizard=false --component.skip.documentation=true
      - ls
      - cd /opt
      - cd coverity
      - cd analysis
      - cd 2020.12
      - cd bin
      - ls
      - ./cov-configure.sh --javascript
      - pip install black==19.3b0 pylama
      - black --check --diff .
      - pylama packet test setup.py
      
  test:
    image: python:${PYTHON_VERSION}
    commands:
      - pip install tox
      - tox -e py$(echo ${PYTHON_VERSION} | sed 's|\.||')
